repo-name = core-kit
thin-manifests = true
sign-manifests = false
profile-formats = portage-2
cache-formats = md5-dict
aliases = gentoo
manifest-hashes = BLAKE2B SHA512
manifest-required-hashes = SHA512
