# Distributed under the terms of the GNU General Public License v2
# Autogen by MARK Devkit

EAPI=7
inherit unpacker

DESCRIPTION="Common CA Certificates PEM files"
HOMEPAGE="https://packages.debian.org/sid/ca-certificates"
SRC_URI="http://ftp.debian.org/debian/pool/main/c/ca-certificates/ca-certificates_20260601_all.deb -> ca-certificates_20260601_all.deb"
LICENSE="MPL-1.1"
SLOT="0"
KEYWORDS="*"
# Commons depends
CDEPEND="!app-misc/c_rehash
	sys-apps/debianutils
	
"
BDEPEND="${CDEPEND}
"
RDEPEND="${CDEPEND}
"
S="${WORKDIR}"
src_unpack() {
	# Do all the work in the image subdir to avoid conflicting with source
	# dirs in ${WORKDIR}.  Need to perform everything in the offset #381937
	mkdir -p "image/${EPREFIX}" || die
	cd "image/${EPREFIX}" || die
	 unpacker_src_unpack
}
src_prepare() {
	cd "image/${EPREFIX}" || die
	default
	eapply -p2 "${FILESDIR}"/${PN}-20150426-root.patch
	local relp=$(echo "${EPREFIX}" | sed -e 's:[^/]\+:..:g')
	sed -i \
	  -e '/="$ROOT/s:ROOT:ROOT'"${EPREFIX}"':' \
	  -e '/RELPATH="\.\./s:"$:'"${relp}"'":' \
	  usr/sbin/update-ca-certificates || die
}
src_compile() {
	cd "image/${EPREFIX}" || die
	mv usr/share/doc/{ca-certificates,${PF}} || die
	(
	  echo "# Automatically generated by ${CATEGORY}/${PF}"
	  echo "# $(date -u)"
	  echo "# Do not edit."
	  cd "usr/share/ca-certificates" || die
	  find * -name '*.crt' | LC_ALL=C sort
	) > etc/ca-certificates.conf
	 sh usr/sbin/update-ca-certificates --root "${S}/image" || die
}
src_install() {
	cp -pPR image/* "${D}"/ || die
	echo 'CONFIG_PROTECT_MASK="/etc/ca-certificates.conf"' > 98ca-certificates
	doenvd 98ca-certificates
}


# vim: filetype=ebuild
